version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py wait_for_db &&
             python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env.docker
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    env_file:
      - ./.env.docker
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A config worker -l INFO
    volumes:
      - .:/app
    env_file:
      - ./.env.docker
    depends_on:
      - db
      - redis
      - app
  celery-beat:
    build:
      context: .
    command: celery -A config beat -l INFO
    volumes:
      - .:/app
    env_file:
      - ./.env.docker
    depends_on:
      - db
      - redis
      - app
volumes:
  pgdata:
