# Generated by Django 3.2.9 on 2021-11-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_currency", models.CharField(default="BTC", max_length=20)),
                ("to_currency", models.CharField(default="USD", max_length=20)),
                ("exchange_rate", models.FloatField()),
                ("last_refreshed", models.DateTimeField(auto_now_add=True)),
                ("timezone", models.CharField(max_length=50)),
                ("bid_price", models.FloatField()),
                ("ask_price", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "quotes"},
        ),
    ]
